##########################################################################
# Author: Jacob Nardone
# File Type: GNU Makefile
# Date Created: 12/29/21
# Description: Simple Java Makefile for programming problems.
##########################################################################


Solution.class: main.java
	@echo Building class files...
	@javac main.java

run: Solution.class
	@java Solution

runonly:
	@java Solution

clean:
	rm -rf Solution.class
