##########################################################################
# Author: Jacob Nardone
# File Type: GNU Makefile
# Date Created: 12/29/21
# Description: Simple Java Makefile for programming problems.
##########################################################################


Chapter_1.class: main.java
	@echo Building class files...
	@javac main.java

run: Chapter_1.class
	@java Chapter_1

runonly:
	@java Chapter_1

clean:
	rm -rf Chapter_1.class
